<CalcDisplay>:
	orientation: 'vertical'

	ResultsDisplay:
		size_hint_y: .2
	ButtonsDisplay:

<ButtonsDisplay>:
	rows: 5
	cols: 4

	canvas:
		Color:
			rgb: 1, 1, 1
		Rectangle:
			size: self.size
	Button:
		id: seven
		text: '7'
	Button:
		id: eight
		text: '8'
	Button:
		id: nine
		text: '9'
	Button:
		id: add
		text: '+'
	Button:
		id: four
		text: '4'
	Button:
		id: five
		text: '5'
	Button:
		id: six
		text: '6'
	Button:
		id: subtract
		text: '-'
	Button:
		id: one
		text: '1'
	Button:
		id: two
		text: '2'
	Button:
		id: three
		text: '3'
	Button:
		id: multiply
		text: 'x'
	Button:
		id: delete
		text: 'DEL'
	Button:
		id: decimal
		text: '.'
	Button:
		id: equals
		text: '='
	Button:
		id: divide
		text: '÷'
